Repository gorilla/mux, pull requests merged in 2018-12, with the labels that each got.

#422 Subroute configuration fixes
  mux.go
  mux_test.go
  regexp.go
  route.go
Labels: needs-review

#424 Add stalebot config
  .github/stale
Labels: needs-review

#425 Update and rename stale to stale.yml
  .github/stale.yml
Labels: build

#431 fix for issue #429
  middleware_test.go
  route.go
Labels: needs-review, work-required
