Repository gorilla/mux, pull requests merged in 2019-06, with the labels that each got.

#484 [WIP] Create CircleCI config
  .circleci/config.yml
  README.md
Labels: build

#489 Fix nil panic in authentication middleware example
  doc.go
Labels: bug, enhancement

#490 Delete .travis.yml
  .travis.yml
Labels: build

#478 Use subtests for middleware tests
  middleware_test.go
Labels: documentation, needs-review

#492 Delete ISSUE_TEMPLATE.md
  ISSUE_TEMPLATE.md
Labels: documentation

#477 Improve CORS Method Middleware
  .circleci/config.yml
  README.md
  example_cors_method_middleware_test.go
  middleware.go
  middleware_test.go
Labels: enhancement, minor-rev-change
