Repository gorilla/mux, pull requests merged in 2019-08, with the labels that each got.

#513 Update README (self-host logo)
  README.md
Labels: documentation

#510 bugfix/subrouter custom methodNotAllowed handler returning 404 (#509)
  mux_test.go
  route.go
Labels: bug

#516 Added capacity to slice creation, when capacity is known
  regexp.go
  route.go
Labels: enhancement
