Repository gorilla/mux, pull requests merged in 2019-07, with the labels that each got.

#495 Update config.yml
  .circleci/config.yml
Labels: build system

#502 Avoid unnecessary conversion
  mux_test.go
Labels: enhancement

#501 Simplify code
  mux.go
Labels: enhancement, needs review

#493 Add documentation for using mux to serve a SPA
  README.md
  go.mod
Labels: documentation

#503 Remove TravisCI badge
  README.md
Labels: documentation
