Repository gorilla/mux, pull requests merged in 2023-07, with the labels that each got.

#718 [GPT-95] Update go version, add tools for verification and testing
  .circleci/config.yml
  .editorconfig
  .github/workflows/issues.yml
  .github/workflows/test.yml
  .gitignore
  Makefile
  README.md
  go.mod
  middleware_test.go
  mux_httpserver_test.go
  mux_test.go
  regexp.go
  regexp_test.go
  route.go
Labels: needs review, build system, size/L

#719 Delete release-drafter.yml
  .github/release-drafter.yml
Labels: size/XS

#720 Delete stale.yml
  .github/stale.yml
Labels: size/S

#721 Delete AUTHORS
  AUTHORS
Labels: size/XS

#722 Update LICENSE
  LICENSE
Labels: size/M

#724 Updated the logo in README.md
  README.md
Labels: size/XS

#723 Update LICENSE
  LICENSE
Labels: size/M

#726 Update issues.yml
  .github/workflows/issues.yml
Labels: size/XS

#727 Update issues.yml
  .github/workflows/issues.yml
Labels: size/XS

#725 run go fmt with Go 1.20
  doc.go
  mux.go
Labels: size/M
