Repository gorilla/mux, pull requests merged in 2023-08, with the labels that each got.

#678 Fix `Single Page Application` example in `README.md` file
  README.md
Labels: size/S

#712 [BUG] Inconsistent HTTP status code on query mismatch
  mux_test.go
  route.go
Labels: size/M

#672 Clarify documentation examples of Route methods
  route.go
Labels: size/S

#708 changed the routeVariables text content.
  README.md
Labels: size/XS

#676 Add GetVarNames()
  README.md
  example_route_vars_test.go
  mux_test.go
  route.go
Labels: size/L
